### ISSUE TITLE
Script tags don't Generate

### ISSUE THREAD

**Issue by ottz0** [ymmooot/nuxt-jsonld#354] opened 2020-04-30 03:57 UTC
I'm using Nuxt.js Universal mode and I've installed according to your docs. I've console.log(items); before the return and it's getting the list however it does not display the script tag in the source code on npm run dev or with npm run generate (npm run start), no Other errors except the script is not injected in the head section in the source code

**Comment by ymmooot** [comment] 2020-05-04 06:27
Please provide a online reproduction by [CodeSandbox](https://codesandbox.io/) or github repo.

**Comment by tdwells90** [comment] 2020-05-19 22:58
I also had this issue, but it was because I was using the plugin in 'client' mode.

```
{
  src: '~/plugins/jsonld.js',
  mode: 'client'
}
```

This might not be helpful to you, but it fixed the issue for me.

**Comment by danieltamas** [comment] 2020-06-26 20:01
Have the same issue. Using it in **spa** mode, removed the `mode: 'client'` and still no tags

**Comment by ymmooot** [comment] 2020-06-27 01:39
@danieltamas Could you give me a reproduction link or some more information to reproduce?
The example project in `/examples/basic` looks work fine in SPA mode as well.

**Comment by danieltamas** [comment] 2020-06-27 13:16
@ymmooot sure thing.

I've put the **ldjson()** method inside the page component, inside a component in the page component, using `mode: spa` with `npm run generate`.

it doesn't event show up. further more, I put a `console.log()` inside the **ldjson()** method, nothing gets triggered.

any pointers are of help

**Comment by ymmooot** [comment] 2020-06-27 19:26
@danieltamas Thank you the information.

I did following steps.

1. clone this repository
2. `cd ./expample/basic`
3. `yarn install`
4. change nuxt.config.js to `spa` mode  
5. `yarn generate`

And checked the `./dist/index.html`, I got json+ld script tags...
Did you register the plugin by adding `plugins: ['@/plugins/jsonld']` to nuxt.config.js?
Or are you using some libraries which affect the `head` part?

**Comment by danieltamas** [comment] 2020-06-27 21:00
hmm..well nuxt uses the `vue-head` library and I do have a config for each page for the head part.
maybe that might be the problem? 

what I can tell for sure is that none of the pages where I have added **ldson** have the actual generated tags.

**Comment by danieltamas** [comment] 2020-06-28 08:17
also did copy the repo. 
an error exists in the **package.json** where **jsonld** is referenced as `nuxt-jsonld: ../../lib` but that folder does not exist.

and the results are the same: no tags in the head. posting the generated html

`

  | <!doctype html>
-- | --
  | <html>
  | <head>
  | <title>example</title><meta data-n-head="1" charset="utf-8"><meta data-n-head="1" name="viewport" content="width=device-width,initial-scale=1"><meta data-n-head="1" data-hid="description" name="description" content="My marvelous Nuxt.js project"><link data-n-head="1" rel="icon" type="image/x-icon" href="/favicon.ico"><link rel="preload" href="/_nuxt/runtime.0adf6c8.js" as="script"><link rel="preload" href="/_nuxt/commons.app.b2c9593.js" as="script"><link rel="preload" href="/_nuxt/app.80afa69.js" as="script">
  | </head>
  | <body>
  | <div id="__nuxt"><style>#nuxt-loading{background:#fff;visibility:hidden;opacity:0;position:absolute;left:0;right:0;top:0;bottom:0;display:flex;justify-content:center;align-items:center;flex-direction:column;animation:nuxtLoadingIn 10s ease;-webkit-animation:nuxtLoadingIn 10s ease;animation-fill-mode:forwards;overflow:hidden}@keyframes nuxtLoadingIn{0%{visibility:hidden;opacity:0}20%{visibility:visible;opacity:0}100%{visibility:visible;opacity:1}}@-webkit-keyframes nuxtLoadingIn{0%{visibility:hidden;opacity:0}20%{visibility:visible;opacity:0}100%{visibility:visible;opacity:1}}#nuxt-loading>div,#nuxt-loading>div:after{border-radius:50%;width:5rem;height:5rem}#nuxt-loading>div{font-size:10px;position:relative;text-indent:-9999em;border:.5rem solid #f5f5f5;border-left:.5rem solid #fff;-webkit-transform:translateZ(0);-ms-transform:translateZ(0);transform:translateZ(0);-webkit-animation:nuxtLoading 1.1s infinite linear;animation:nuxtLoading 1.1s infinite linear}#nuxt-loading.error>div{border-left:.5rem solid #ff4500;animation-duration:5s}@-webkit-keyframes nuxtLoading{0%{-webkit-transform:rotate(0);transform:rotate(0)}100%{-webkit-transform:rotate(360deg);transform:rotate(360deg)}}@keyframes nuxtLoading{0%{-webkit-transform:rotate(0);transform:rotate(0)}100%{-webkit-transform:rotate(360deg);transform:rotate(360deg)}}</style><script>window.addEventListener("error",function(){var e=document.getElementById("nuxt-loading");e&&(e.className+=" error")})</script><div id="nuxt-loading" aria-live="polite" role="status"><div>Loading...</div></div></div><script>window.__NUXT__={config:{},staticAssetsBase:void 0}</script>
  | <script src="/_nuxt/runtime.0adf6c8.js"></script><script src="/_nuxt/commons.app.b2c9593.js"></script><script src="/_nuxt/app.80afa69.js"></script></body>
  | </html>
  |  

`

**Comment by ymmooot** [comment] 2020-06-29 03:34
Sorry I forgot to write build step. 🙇 

1. clone this repository
2. `yarn build` 👈
3. `cd ./expample/basic`
4. `yarn install`
5. change nuxt.config.js to `spa` mode
6. `yarn generate`

**Comment by ymmooot** [comment] 2020-06-29 03:38
> I do have a config for each page for the head part.

Component's `head` will be automatically merged with the result of the jsonld method.
So it is no problem.

**Comment by danieltamas** [comment] 2020-06-29 06:06
now getting this

`yarn run v1.22.0
$ rimraf lib
$ tsc -p .
/bin/sh: tsc: command not found`

**Comment by ymmooot** [comment] 2020-06-29 15:45
Oh, I will add dependencies to build typescript codes.

I guess you need to `yarn install` before `yarn build`.
Sorry for lacking of preparation to develop.

**Comment by danieltamas** [comment] 2020-06-29 17:22
no worries. the objective is to get it up and running :) maybe someone else has the same issues and they'll find this useful.
thank you for taking the time to do it

**Comment by danieltamas** [comment] 2020-06-30 09:56
@ymmooot following up here. now everything shows up with one mention ( error on my side ): 
- was looking at the generated result and no `ld+json` in the head part

That threw me off. In the DOM the tags show up properly. 
Sorry about that as well. How hard would it be to add this to the `generate|export` hook ?
Having a this tag generated statically makes it easier for crawlers

**Comment by ymmooot** [comment] 2020-06-30 10:30
The static HTML files that are the result of `yarn generate` of the examples in this repository have an `application/ld+json` tag.
I guess there is a library affecting `head` and `nuxt-jsonld` fails to merge.

**Comment by danieltamas** [comment] 2020-06-30 12:04
hmmmm..... now you made me wonder. currently I use `npm run build && npm run export` as with `nuxt 2.13.2` . cannot figure it out for the moment ( what's causing this )

**Comment by ymmooot** [comment] 2020-06-30 17:30
Results of `export` command of nuxt2.13.2 have jsonld script tags too.

I want to reproduce it.
Could you tell me more details of your `package.json` and `nuxt.config.js`?
I need to know what packages you are using and how you configure nuxt.

**Comment by snaix93** [comment] 2021-01-23 10:00
Getting a similar problem. Installed the package successfully and the code is running as I can see in console:
        ```
{@context: "https://schema.org", @type: "BreadcrumbList", itemListElement: Array(3)}
        @context: "https://schema.org"
        @type: "BreadcrumbList"
        itemListElement: Array(3)
        0: {@type: "ListItem", position: 1, item: {…}}
        1: {@type: "ListItem", position: 2, item: {…}}
        2: {@type: "ListItem", position: 3, item: {…}}
        length: 3
        __proto__: Array(0)
        __proto__: Object
```


But after I run :
npm ci or npm install
npm run generate, 
npm run start

The data is not displayed when I hit ctrl+U

My config

```
  ssr: false,
  mode: 'spa',
  
    plugins: [
          { src: '~/plugins/plugin.js', ssr:false },
          { src: '~/plugins/localStorage.js', ssr:false },
          '@/plugins/vue-api-query',
          '@/plugins/jsonld',
  ],

```

jsonltd:
```
import Vue from 'vue';
import NuxtJsonld from 'nuxt-jsonld';

Vue.use(NuxtJsonld);
```

Json ltd located on the same lvl as data
 ```
 jsonld() {
    console.log('here');
    const items = this.breadcrumbs.map((item, index) => ({
      '@type': 'ListItem',
      position: index + 1,
      item: {
        '@id': item.url,
        name: item.text,
      },
    }));
    console.log({
      '@context': 'https://schema.org',
      '@type': 'BreadcrumbList',
      itemListElement: items,
    });
    return {
      '@context': 'https://schema.org',
      '@type': 'BreadcrumbList',
      itemListElement: items,
    };
  },
```
Can you help please?

**Comment by snaix93** [comment] 2021-01-23 11:16
Actually it's working. I am not able to see it when pressing ctrl + u butt google data structured test sees everything with no errors. Thank you :)

**Comment by ymmooot** [comment] 2021-02-01 11:32
This issue is old.
Please open new issue when having problems with current version of the plugin.

**Closed by ymmooot** 2021-02-01 11:32 UTC
