### ISSUE TITLE
Child route don't change breadcrumb

### ISSUE THREAD

**Issue by forna91** [ymmooot/nuxt-jsonld#723] opened 2021-09-21 07:35 UTC
Like in title, the child route don't change my jsondl, any work around??

**Comment by ymmooot** [comment] 2021-10-05 10:14
@forna91 Thank you for your report.
Let me reproduce the problem. 
Please wait 🙏

**Comment by ymmooot** [comment] 2021-11-18 16:31
I will close this issue because I can get enough information to reproduce the bug.
Please reopen if needed.

**Closed by ymmooot** 2021-11-18 16:31 UTC
