### ISSUE TITLE
Duplicate structured data items in Google structured data test tool

### ISSUE THREAD

**Issue by IgorOleniuk** [ymmooot/nuxt-jsonld#423] opened 2020-07-17 15:13 UTC
https://github.com/ymmooot/nuxt-jsonld/blob/12a6d8b936de9b686c3e16f54a6cf8f69d75480f/src/mergeHead.ts#L24

I'm testing a structured data on the website. And it shows duplicate structured data items.
<img width="700" alt="Screenshot 2020-07-17 at 18 02 42" src="https://user-images.githubusercontent.com/51889774/87800949-b86bbd80-c857-11ea-8d96-1ed46280763b.png">

There is a duplicated structured data code after closing html tag:

<img width="686" alt="Screenshot 2020-07-17 at 18 03 41" src="https://user-images.githubusercontent.com/51889774/87801066-dc2f0380-c857-11ea-897c-fd9d680902d0.png">

But when I'm looking in the page source there is nothing after closing html tag.

How can I remove an excessive item?

I post this issue on StackOverflow here - https://stackoverflow.com/questions/62942330/duplicate-structured-data-items-in-google-structured-data-test-tool?noredirect=1#comment111311866_62942330 and I was recommended to open an issue here.

**Comment by ymmooot** [comment] 2020-07-17 15:44
Hi @IgorOleniuk ✋ 

I guess Google structured data testing tool accesses the site and run your JavaScript code.
The ld+json script tag after html closing tag may be inserted by JavaScript on client-side.

Could you check that you use `jsonld()` method in components that rendered only on client-side, and the result of `jsonld()` method duplicates ld+json script tags rendered on server-side?

**Comment by IgorOleniuk** [comment] 2020-07-17 16:51
Hi @ymmooot thanks for your reply!

It's a static website, I run nuxt generate.

Here's a screenshot from page source:

<img width="1407" alt="Screenshot 2020-07-17 at 19 49 00" src="https://user-images.githubusercontent.com/51889774/87810991-9168b800-c866-11ea-9c6e-18733c8684a8.png">

**Comment by ymmooot** [comment] 2020-07-17 17:06
I see, you should check your client-side `jsonld()` makes duplicate tags with generated ld+script tags.
Could you show me the component source code that using `jsonld()` ?

**Comment by IgorOleniuk** [comment] 2020-07-17 18:03
> I see, you should check your client-side `jsonld()` makes duplicate tags with generated ld+script tags.
> Could you show me the component source code that using `jsonld()` ?

Sure, here it is:

<img width="1440" alt="Screenshot 2020-07-17 at 21 01 39" src="https://user-images.githubusercontent.com/51889774/87816946-c67a0800-c870-11ea-9d21-95b97e386329.png">
<img width="1440" alt="Screenshot 2020-07-17 at 21 01 50" src="https://user-images.githubusercontent.com/51889774/87816959-c974f880-c870-11ea-9e9c-043e3a50370a.png">

**Comment by ymmooot** [comment] 2020-07-17 18:31
Thank you for the code.
I figured out the reason.

1. `nuxt generate` makes static HTML files having jsonld tag like below. The data-hid is also made by this command.
 ```html
<script data-n-head="ssr" data-hid="nuxt-jsonld-6" type="application/ld+json">{ some json }</script>
<!-- data-hid="nuxt-jsonld-6" is decided when generate (6 is just an example)-->
```
2. When structured data testing tool requests to the hosted HTML file, it will get the `data-hid="nuxt-jsonld-6"` tag.
3. After hydration, your `mounted()` function will be modify title and jsonld tag will be recreated by reactivity.
4. So hid will be changed, but json contents will not be changed depends on the title.
5. Testing tool recognizes the recreated tag as different, new, and duplicated content tag.

I do not think you have to fix this. (It is just testing tools behavior.)
If you are worried, copy the title for `jsonld()` method and prevent the influence of `mounted()` function

**Comment by IgorOleniuk** [comment] 2020-07-17 20:44
> Thank you for the code.
> I figured out the reason.
> 
> 1. `nuxt generate` makes static HTML files having jsonld tag like below. The data-hid is also made by this command.
> 
> ```
> <script data-n-head="ssr" data-hid="nuxt-jsonld-6" type="application/ld+json">{ some json }</script>
> 
> ```
> 
> 1. When structured data testing tool requests to the hosted HTML file, it will get the `data-hid="nuxt-jsonld-6"` tag.
> 2. After hydration, your `mounted()` function will be modify title and jsonld tag will be recreated by reactivity.
> 3. So hid will be changed, but json contents will not be changed depends on the title.
> 4. Testing tool recognizes the recreated tag as different, new, and duplicated content tag.
> 
> I do not think you have to fix this. (It is just testing tools behavior.)
> If you are worried, copy the title for `jsonld()` method and prevent the influence of `mounted()` function

Thank you for your answer. 
I tried to delete the hole mounted block but it didn't help.

**Comment by ymmooot** [comment] 2020-07-17 20:51
hmm...
I guess there is clinet-side code besides `mounted` recreates jsonld.

**Comment by ymmooot** [comment] 2020-07-17 20:54
Anyway, using private Vue _id for hid is an existing issue.
I will investigate this as well.

(I would appreciate if you make reproduction link with codesandbox.io!)

**Comment by IgorOleniuk** [comment] 2020-07-17 21:17
> Anyway, using private Vue _id for hid is an existing issue (#219).
> I will investigate this as well.
> 
> (I would appreciate if you make reproduction link with codesandbox.io!)

Oh, I'm so sorry. I wish I could but it's a client project and I don't have enough permissions to publish it fully.

**Comment by ymmooot** [comment] 2020-07-17 21:21
It's OK not to publish you entire app.
I need small code to reproducing.
Please make similar code causing same error if you have time. 👌

**Closed** 2021-08-04 03:53 UTC
Labels: question

**Comment by leopoldkristjansson** [comment] 2024-11-13 10:59
I have been struggling with these duplication issues for a while. Both seeing duplicates in testing tools like https://validator.schema.org as well as in Google Search console.

<kbd><img width="1608" alt="Screenshot 2024-11-13 at 11 52 42" src="https://github.com/user-attachments/assets/8d37dd57-496b-42ea-87c2-2c61d5291f1a"></kbd>

By using a [callOnce](https://nuxt.com/docs/api/utils/call-once) wrapper (Nuxt 3.9 and above) it seems to work as expected. At least for the testing tools. Still waiting for the Google Search Console validation to go through. Example:

```ts
await callOnce(async () => {
  useJsonld({
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: myFaqItems.map((faq) => ({
      '@type': 'Question',
      name: faq.title,
      acceptedAnswer: {
        '@type': 'Answer',
        text: faq.description,
      },
    })),
  })
})

```
